[general]
admin = 123456789 # Replace me!
prefix = "$"
cooldowntime = 0
noreplylist = "data/noreplyusers.json"
neverreplylist = "data/neverreplyusers.json"
allowedchannels = "data/allowedchannels.json"
allowedusers = "data/allowedusers.json"
sentiment-analysis-ratio = 1 # Higher means less messages are checked, 1 means all are checked
sentiment-analysis-cache = 50 # How many messages to check before warning moderators

[channels]
report-users-channel-id = 123456789 # Replace me!
playtesters-channel-id = 123456789 # Replace me!
playtester-proxy-ping-allowed-channel-ids = [
    123, # Replace me!
    456, # Replace me!
    789, # Replace me!
]
thunderstore-releases-channel-id = 123456789 # Replace me!
sentiment-analysis-channels = [
    123, # Replace me!
    456, # Replace me!
    789, # Replace me!
]
sentiment-analysis-warn-channel = 123456789 # Replace me!

[tokens]
discord = "REPLACE-ME"
github = ""

[roles]
playtester-role-id = 123456789 # Replace me!
ping-privileged-role-ids = [
    123,  # Replace me!
    456,  # Replace me!
    789,  # Replace me!
]
