name: Format check
on: [push, pull_request]


jobs:
  format-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Format check with ruff
      run: |
        pip install ruff
        ruff format --check
